# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
brave = User.create email: "bravery@gmail.com", password: "omghalo3"

brave.venues.create(address: "701 SEVENTH ST NORTHWEST WASHINGTON, DISTRICT OF COLUMBIA 20001 " , venue_title: "Regal Gallery Place Stadium 14" , venue_describe: "The goal of Regal Business Events is to deliver the best possible DC movie theater rental experience from start to finish. Our team can help you from the planning stages and as you go through the coordination and execution of your business meetings and events. Adding giant screens, surround sound audio, stunning HD and comfortable stadium seating means your event engages your audience like no other medium can. If you want to rent a movie theater in DC and transform your business meeting experience, you can contact us today to explore the possibilities." , contact: "866-507-3425" , capacity: "2800")
brave.venues.create(address: "1705 DESALES NW WASHINGTON, DISTRICT OF COLUMBIA 20036 " , venue_title: "Breather DeSales" , venue_describe: "Get your team together in this sizable space, which seats 14 around a large conference table. Masculine accents like the black leather chair and navy rug to give the space a serious, no nonsense vibe that’s perfect for getting down to business." , contact: "877-711-5990" , capacity: "50")
brave.venues.create(address: "4400 MASSACHUSETTS AVE NW WASHINGTON, DISTRICT OF COLUMBIA 20016", venue_title: "American University" , venue_describe: "American University, a national campus arboretum, is conveniently located on Massachusetts Ave., in an urban residential neighborhood in Washington, D.C., less than five miles from the White House. Conference guests can take the Metro or walk within a few miles to some of DC's most historic sites, along with experiencing, art, history, culture, shopping, entertainment, and great food! " , contact: "202.885.8247" , capacity: "1000")
brave.venues.create(address: "20 F STREET, NW WASHINGTON, DISTRICT OF COLUMBIA 20001" , venue_title: "20 F Street NW Conference Center" , venue_describe: "Located on Capitol Hill and within walking distance of the Union Station Metro, the 20 F Street NW Conference Center is a new state-of-the art meeting and conference facility. With one large conference room that can accommodate up to 200ppl and two smaller boardrooms for up to 24pp it has all the amenities you'll need for your next corporate training session, sales meeting, board retreat, networking event, corporate dinner or special events reception. Looking for a venue with a view? 20 F Street's tented south roof terrace provides a unique site for your special event. With spectacular views of the Washington Monument and the Capitol Dome it can accommodate up to 200pp for a cocktail reception or 110pp for a seated meal. Hosting a rooftop event will ensure you and your guests will share an experience that will be remembered for a lifetime." , contact: "202-672-1515" , capacity: "200")
brave.venues.create(address: "172 FLEET STREET NATIONAL HARBOR-MD, DISTRICT OF COLUMBIA" , venue_title: "Bobby McKey's Dueling Piano Bar" , venue_describe: "With exposed brick walls and lofty ceilings, Bobby McKey's offers a rustic cool private event space. Configured of open table seating surrounding a stage, the space is ideal for large meetings and transforms easily for cocktail receptions and networking mixers.  Our space is designed to welcome any crowd or party in search of an extraordinary way to celebrate with the option to add our house Dueling Piano Show, entertaining guests with all request music. We use cutting-edge technology to provide your event with state-of-the-art sound and lighting.  Just a short stroll from the Gaylord National Convention center and the soon to be MGM National Harbor, Bobby McKey's location puts you in a prime spot and just minutes from D.C. and VA.", contact: "301-602-8852" , capacity: "500")
brave.venues.create(address: "703 EDGEWOOD STREET NE WASHINGTON, DISTRICT OF COLUMBIA 20017 ", venue_title: "Mess Hall" , venue_describe: "Located in the heart of Washington, DC's Brookland neighborhood, Mess Hall offers a unique venue for those looking to create killer events guests won’t forget. Our 2,000 square feet of renovated warehouse space boasts 18 foot ceilings, vintage industrial décor, and a multi-room configuration, allowing you to bring your specific vision to life. Mess Hall has played host to sold-out events featuring buzz-worthy and up-and-coming chefs and restaurants as well as private events for rock star companies including DC Brau, Redfin, and Split.", contact: "(202) 413-2768", capacity: "200")
brave.venues.create(address: "1333 14TH STREET NW WASHINGTON, DISTRICT OF COLUMBIA 20005", venue_title: "Fathom Gallery" , venue_describe: "Located in the heart of Logan Circle, Fathom Gallery boasts a 2500 sqft outdoor rooftop garden just outside the 1250 sqft gallery space. The spaces are ideal for weddings, refined art showings, cocktail receptions, and corporate retreats / meetings for events up-to 125 guests." , contact: "202-588-8111", capacity: "125")
brave.venues.create(address: "2017 I ST NW WASHINGTON, DISTRICT OF COLUMBIA 20006", venue_title: "Arts Club of Washington" , venue_describe: "A beautifully furnished historic mansion, once the home of President James Monroe. A central and convenient location, just four blocks from the White House. Gallery spaces that feature rotating exhibits by nationally renowned artists. An expansive walled garden and terrace. A full-service food, beverage, and event-support operation.", contact: "202-331-7282" , capacity: "300")
brave.venues.create(address: "529 14TH ST NW WASHINGTON, DISTRICT OF COLUMBIA 20045", venue_title: "The National Press Club", venue_describe: "For over 100 years, The National Press Club has hosted the most historic events in Washington, featuring U.S. presidents, kings, queens, prime ministers, Cabinet members, governors, members of Congress and influential leaders in business, entertainment, sport and society.   What began in 1908 as a private social club for journalists has evolved into a world-class business and conference center that hosts more than 2.000 public and private events annually.  Your guests will be surrounded by a century of media history; they’ll be gazing at the walls and pictures of who’s been here, and talking about your event for years to come.", contact: "202-662-7587", capacity: "1500")
brave.venues.create(address: "3111 K STREET NW WASHINGTON, DISTRICT OF COLUMBIA 20007", venue_title: "AMC Georgetown 14", venue_describe: "At AMC Georgetown 14, we specialize in the amazing! With our help, you can tap into the excitement of a movie premier to inspire your next business meeting. With our state of the art audio/visual, your presentation will shine with big screen impact." , contact: "rentals@amctheatres.com" , capacity: "2100")
brave.venues.create(address: "727 15 STREET NW WASHINGTON, DISTRICT OF COLUMBIA 20005", venue_title: "Breather 15th Street" , venue_describe: "The city architecture informs this room’s design with classic, clean lines and subdued tones. Designed for teams, it features a sitting area, white board, on-site restroom and two expansive cork tables to help pin down your ideas." , contact: "877-711-5990" , capacity: "150")